// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyGiaoNhan_UNETI5_TI17A4HN.Models;

#nullable disable

namespace QuanLyGiaoNhan_UNETI5_TI17A4HN.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260922022146_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.DonGiaoHang", b =>
                {
                    b.Property<int>("MaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDon"));

                    b.Property<string>("DiaChiNhan")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("KhoiLuong")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaKhuVuc")
                        .HasColumnType("int");

                    b.Property<int>("MaLoaiHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayGiaoDuKien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PhiVanChuyen")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SoDienThoaiNguoiNhan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenNguoiNhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDon");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaKhuVuc");

                    b.HasIndex("MaLoaiHang");

                    b.ToTable("DonGiaoHangs");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaKhachHang");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique();

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.KhuVuc", b =>
                {
                    b.Property<int>("MaKhuVuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhuVuc"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("PhiCoBan")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenKhuVuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaKhuVuc");

                    b.HasIndex("TenKhuVuc")
                        .IsUnique();

                    b.ToTable("KhuVucs");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.LichSuGiaoNhan", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<int>("MaDon")
                        .HasColumnType("int");

                    b.Property<string>("NguoiThucHien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThaiCu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThaiMoi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLichSu");

                    b.HasIndex("MaDon");

                    b.ToTable("LichSuGiaoNhans");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.LoaiHang", b =>
                {
                    b.Property<int>("MaLoaiHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiHang"));

                    b.Property<decimal>("HeSoPhuThu")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenLoaiHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaLoaiHang");

                    b.HasIndex("TenLoaiHang")
                        .IsUnique();

                    b.ToTable("LoaiHangs");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.NhanVienGiaoHang", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KhuVucPhuTrach")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique();

                    b.ToTable("NhanVienGiaoHangs");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.PhanCongGiaoHang", b =>
                {
                    b.Property<int>("MaPhanCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhanCong"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaDon")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<int>("MaPhuongTien")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayBatDauGiao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayNhanHang")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayPhanCong")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaPhanCong");

                    b.HasIndex("MaDon");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaPhuongTien");

                    b.ToTable("PhanCongGiaoHangs");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.PhuongTien", b =>
                {
                    b.Property<int>("MaPhuongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhuongTien"));

                    b.Property<string>("BienSo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiPhuongTien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TaiTrongToiDa")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("MaPhuongTien");

                    b.HasIndex("BienSo")
                        .IsUnique();

                    b.ToTable("PhuongTiens");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.DonGiaoHang", b =>
                {
                    b.HasOne("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.KhachHang", "KhachHang")
                        .WithMany("DonGiaoHangs")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.KhuVuc", "KhuVuc")
                        .WithMany("DonGiaoHangs")
                        .HasForeignKey("MaKhuVuc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.LoaiHang", "LoaiHang")
                        .WithMany("DonGiaoHangs")
                        .HasForeignKey("MaLoaiHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("KhuVuc");

                    b.Navigation("LoaiHang");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.KhachHang", b =>
                {
                    b.HasOne("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("KhachHang")
                        .HasForeignKey("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.KhachHang", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.LichSuGiaoNhan", b =>
                {
                    b.HasOne("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.DonGiaoHang", "DonGiaoHang")
                        .WithMany("LichSuGiaoNhans")
                        .HasForeignKey("MaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonGiaoHang");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.NhanVienGiaoHang", b =>
                {
                    b.HasOne("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("NhanVienGiaoHang")
                        .HasForeignKey("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.NhanVienGiaoHang", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.PhanCongGiaoHang", b =>
                {
                    b.HasOne("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.DonGiaoHang", "DonGiaoHang")
                        .WithMany("PhanCongGiaoHangs")
                        .HasForeignKey("MaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.NhanVienGiaoHang", "NhanVienGiaoHang")
                        .WithMany("PhanCongGiaoHangs")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.PhuongTien", "PhuongTien")
                        .WithMany("PhanCongGiaoHangs")
                        .HasForeignKey("MaPhuongTien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonGiaoHang");

                    b.Navigation("NhanVienGiaoHang");

                    b.Navigation("PhuongTien");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.DonGiaoHang", b =>
                {
                    b.Navigation("LichSuGiaoNhans");

                    b.Navigation("PhanCongGiaoHangs");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.KhachHang", b =>
                {
                    b.Navigation("DonGiaoHangs");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.KhuVuc", b =>
                {
                    b.Navigation("DonGiaoHangs");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.LoaiHang", b =>
                {
                    b.Navigation("DonGiaoHangs");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.NhanVienGiaoHang", b =>
                {
                    b.Navigation("PhanCongGiaoHangs");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.PhuongTien", b =>
                {
                    b.Navigation("PhanCongGiaoHangs");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_TI17A4HN.Models.TaiKhoan", b =>
                {
                    b.Navigation("KhachHang");

                    b.Navigation("NhanVienGiaoHang");
                });
#pragma warning restore 612, 618
        }
    }
}
