// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyGiaoNhan_UNETI5_DHTI17A4.Data;

#nullable disable

namespace QuanLyGiaoNhan_UNETI5_DHTI17A4.Data.Migrations
{
    [DbContext(typeof(QuanLyGiaoNhanDbContext))]
    [Migration("20260929093034_KhoiTaoCsdl")]
    partial class KhoiTaoCsdl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.DonGiaoHang", b =>
                {
                    b.Property<int>("MaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDon"));

                    b.Property<string>("DiaChiNhan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("KhoiLuong")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaKhuVuc")
                        .HasColumnType("int");

                    b.Property<int>("MaLoaiHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayGiaoDuKien")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayHoanTat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PhiCoBan")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("PhiVanChuyen")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("PhuPhiKhoiLuong")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("PhuPhiLoaiHang")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("SoDienThoaiNguoiNhan")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenNguoiNhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("MaDon");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaKhuVuc");

                    b.HasIndex("MaLoaiHang");

                    b.HasIndex("NgayTao");

                    b.HasIndex("TrangThai");

                    b.ToTable("DonGiaoHangs", t =>
                        {
                            t.HasCheckConstraint("CK_DonGiaoHang_KhoiLuong", "[KhoiLuong] > 0");

                            t.HasCheckConstraint("CK_DonGiaoHang_Phi", "[PhiVanChuyen] >= 0");
                        });
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("MaKhachHang");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique()
                        .HasFilter("[MaTaiKhoan] IS NOT NULL");

                    b.HasIndex("SoDienThoai");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.KhuVuc", b =>
                {
                    b.Property<int>("MaKhuVuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhuVuc"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("PhiCoBan")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("TenKhuVuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("MaKhuVuc");

                    b.HasIndex("TenKhuVuc")
                        .IsUnique();

                    b.ToTable("KhuVucs", t =>
                        {
                            t.HasCheckConstraint("CK_KhuVuc_PhiCoBan", "[PhiCoBan] >= 0");
                        });
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.LichSuGiaoNhan", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<int>("MaDon")
                        .HasColumnType("int");

                    b.Property<string>("NguoiThucHien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("TrangThaiCu")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TrangThaiMoi")
                        .HasColumnType("tinyint");

                    b.HasKey("MaLichSu");

                    b.HasIndex("MaDon", "ThoiGian");

                    b.ToTable("LichSuGiaoNhans");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.LoaiHang", b =>
                {
                    b.Property<int>("MaLoaiHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiHang"));

                    b.Property<decimal>("HeSoPhuThu")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenLoaiHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("MaLoaiHang");

                    b.HasIndex("TenLoaiHang")
                        .IsUnique();

                    b.ToTable("LoaiHangs", t =>
                        {
                            t.HasCheckConstraint("CK_LoaiHang_HeSoPhuThu", "[HeSoPhuThu] >= 0");
                        });
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.NhanVienGiaoHang", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaKhuVucPhuTrach")
                        .HasColumnType("int");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("MaKhuVucPhuTrach");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique()
                        .HasFilter("[MaTaiKhoan] IS NOT NULL");

                    b.ToTable("NhanVienGiaoHangs");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.PhanCongGiaoHang", b =>
                {
                    b.Property<int>("MaPhanCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhanCong"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte?>("KetQua")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("LyDoThatBai")
                        .HasColumnType("tinyint");

                    b.Property<int>("MaDon")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<int>("MaPhuongTien")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayBatDauGiao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayNhanHang")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayPhanCong")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiPhanCong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("MaPhanCong");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaPhuongTien");

                    b.HasIndex("MaDon", "TrangThai");

                    b.ToTable("PhanCongGiaoHangs");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.PhuongTien", b =>
                {
                    b.Property<int>("MaPhuongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhuongTien"));

                    b.Property<string>("BienSo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiPhuongTien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TaiTrongToiDa")
                        .HasColumnType("decimal(10,2)");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("MaPhuongTien");

                    b.HasIndex("BienSo")
                        .IsUnique();

                    b.ToTable("PhuongTiens", t =>
                        {
                            t.HasCheckConstraint("CK_PhuongTien_TaiTrong", "[TaiTrongToiDa] > 0");
                        });
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.DonGiaoHang", b =>
                {
                    b.HasOne("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.KhachHang", "KhachHang")
                        .WithMany("DonGiaoHangs")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.KhuVuc", "KhuVuc")
                        .WithMany("DonGiaoHangs")
                        .HasForeignKey("MaKhuVuc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.LoaiHang", "LoaiHang")
                        .WithMany("DonGiaoHangs")
                        .HasForeignKey("MaLoaiHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("KhuVuc");

                    b.Navigation("LoaiHang");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.KhachHang", b =>
                {
                    b.HasOne("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("KhachHang")
                        .HasForeignKey("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.KhachHang", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.LichSuGiaoNhan", b =>
                {
                    b.HasOne("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.DonGiaoHang", "DonGiaoHang")
                        .WithMany("LichSus")
                        .HasForeignKey("MaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonGiaoHang");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.NhanVienGiaoHang", b =>
                {
                    b.HasOne("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.KhuVuc", "KhuVucPhuTrach")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaKhuVucPhuTrach")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("NhanVienGiaoHang")
                        .HasForeignKey("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.NhanVienGiaoHang", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("KhuVucPhuTrach");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.PhanCongGiaoHang", b =>
                {
                    b.HasOne("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.DonGiaoHang", "DonGiaoHang")
                        .WithMany("PhanCongs")
                        .HasForeignKey("MaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.NhanVienGiaoHang", "NhanVien")
                        .WithMany("PhanCongs")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.PhuongTien", "PhuongTien")
                        .WithMany("PhanCongs")
                        .HasForeignKey("MaPhuongTien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonGiaoHang");

                    b.Navigation("NhanVien");

                    b.Navigation("PhuongTien");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.DonGiaoHang", b =>
                {
                    b.Navigation("LichSus");

                    b.Navigation("PhanCongs");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.KhachHang", b =>
                {
                    b.Navigation("DonGiaoHangs");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.KhuVuc", b =>
                {
                    b.Navigation("DonGiaoHangs");

                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.LoaiHang", b =>
                {
                    b.Navigation("DonGiaoHangs");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.NhanVienGiaoHang", b =>
                {
                    b.Navigation("PhanCongs");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.PhuongTien", b =>
                {
                    b.Navigation("PhanCongs");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.TaiKhoan", b =>
                {
                    b.Navigation("KhachHang");

                    b.Navigation("NhanVienGiaoHang");
                });
#pragma warning restore 612, 618
        }
    }
}
