// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyGiaoNhan_UNETI5_DHTI17A4.Data;

#nullable disable

namespace QuanLyGiaoNhan_UNETI5_DHTI17A4.Data.Migrations
{
    [DbContext(typeof(QuanLyGiaoNhanDbContext))]
    partial class QuanLyGiaoNhanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.BannerTrangChu", b =>
                {
                    b.Property<int>("MaBanner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBanner"));

                    b.Property<string>("Anh")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ChuNut")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("HienThi")
                        .HasColumnType("bit");

                    b.Property<string>("LienKet")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MaBanner");

                    b.HasIndex("HienThi", "ThuTu");

                    b.ToTable("BannerTrangChus");

                    b.HasData(
                        new
                        {
                            MaBanner = 1,
                            Anh = "/img/banner/banner-1.svg",
                            ChuNut = "Tạo đơn ngay",
                            HienThi = true,
                            LienKet = "/DangNhap/DangKy",
                            MoTa = "Lấy hàng tận nơi trong ngày, phí hiển thị ngay khi tạo đơn.",
                            NgayTao = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThuTu = 1,
                            TieuDe = "Giao hàng nhanh, theo dõi minh bạch từng bước"
                        },
                        new
                        {
                            MaBanner = 2,
                            Anh = "/img/banner/banner-2.svg",
                            ChuNut = "Tìm hiểu thêm",
                            HienThi = true,
                            LienKet = "/TrangChu/ChiTietTinTuc/2",
                            MoTa = "Tiền thu hộ được nộp về công ty và trả lại người gửi sau khi đối soát.",
                            NgayTao = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThuTu = 2,
                            TieuDe = "Thu hộ tiền hàng an toàn, đối soát rõ ràng"
                        },
                        new
                        {
                            MaBanner = 3,
                            Anh = "/img/banner/banner-3.svg",
                            ChuNut = "Tra cứu đơn",
                            HienThi = true,
                            LienKet = "/TrangChu/TraCuu",
                            MoTa = "Chỉ cần mã đơn và số điện thoại người nhận.",
                            NgayTao = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThuTu = 3,
                            TieuDe = "Tra cứu hành trình đơn hàng mọi lúc"
                        });
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.DonGiaoHang", b =>
                {
                    b.Property<int>("MaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDon"));

                    b.Property<string>("AnhGiaoHang")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DiaChiNhan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("KhoiLuong")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("MaGiaoDichNop")
                        .HasColumnType("int");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaKhuVuc")
                        .HasColumnType("int");

                    b.Property<int>("MaLoaiHang")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDoiSoat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayGiaoDuKien")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayHoanTat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<byte>("NguoiTraPhi")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("PhiCoBan")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("PhiVanChuyen")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("PhuPhiKhoiLuong")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("PhuPhiLoaiHang")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("SoDienThoaiNguoiNhan")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenNguoiNhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TienThuHo")
                        .HasColumnType("decimal(18,0)");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("MaDon");

                    b.HasIndex("MaGiaoDichNop");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaKhuVuc");

                    b.HasIndex("MaLoaiHang");

                    b.HasIndex("NgayTao");

                    b.HasIndex("TrangThai");

                    b.ToTable("DonGiaoHangs", t =>
                        {
                            t.HasCheckConstraint("CK_DonGiaoHang_KhoiLuong", "[KhoiLuong] > 0");

                            t.HasCheckConstraint("CK_DonGiaoHang_Phi", "[PhiVanChuyen] >= 0");

                            t.HasCheckConstraint("CK_DonGiaoHang_TienThuHo", "[TienThuHo] >= 0");
                        });
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.GiaoDichVi", b =>
                {
                    b.Property<int>("MaGiaoDich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiaoDich"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte>("Loai")
                        .HasColumnType("tinyint");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXuLy")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiXuLy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("ThongTinThanhToan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("MaGiaoDich");

                    b.HasIndex("TrangThai");

                    b.HasIndex("MaNhanVien", "NgayTao");

                    b.ToTable("GiaoDichVis", t =>
                        {
                            t.HasCheckConstraint("CK_GiaoDichVi_SoTien", "[SoTien] >= 0");
                        });
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("MaKhachHang");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique()
                        .HasFilter("[MaTaiKhoan] IS NOT NULL");

                    b.HasIndex("SoDienThoai");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.KhuVuc", b =>
                {
                    b.Property<int>("MaKhuVuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhuVuc"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("PhiCoBan")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("TenKhuVuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("MaKhuVuc");

                    b.HasIndex("TenKhuVuc")
                        .IsUnique();

                    b.ToTable("KhuVucs", t =>
                        {
                            t.HasCheckConstraint("CK_KhuVuc_PhiCoBan", "[PhiCoBan] >= 0");
                        });
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.LichSuGiaoNhan", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<int>("MaDon")
                        .HasColumnType("int");

                    b.Property<string>("NguoiThucHien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("TrangThaiCu")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TrangThaiMoi")
                        .HasColumnType("tinyint");

                    b.HasKey("MaLichSu");

                    b.HasIndex("ThoiGian");

                    b.HasIndex("MaDon", "ThoiGian");

                    b.ToTable("LichSuGiaoNhans");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.LoaiHang", b =>
                {
                    b.Property<int>("MaLoaiHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiHang"));

                    b.Property<decimal>("HeSoPhuThu")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenLoaiHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("MaLoaiHang");

                    b.HasIndex("TenLoaiHang")
                        .IsUnique();

                    b.ToTable("LoaiHangs", t =>
                        {
                            t.HasCheckConstraint("CK_LoaiHang_HeSoPhuThu", "[HeSoPhuThu] >= 0");
                        });
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.NhanVienGiaoHang", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaKhuVucPhuTrach")
                        .HasColumnType("int");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("MaKhuVucPhuTrach");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique()
                        .HasFilter("[MaTaiKhoan] IS NOT NULL");

                    b.ToTable("NhanVienGiaoHangs");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.PhanCongGiaoHang", b =>
                {
                    b.Property<int>("MaPhanCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhanCong"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte?>("KetQua")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("LyDoThatBai")
                        .HasColumnType("tinyint");

                    b.Property<int>("MaDon")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<int>("MaPhuongTien")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayBatDauGiao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayNhanHang")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayPhanCong")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiPhanCong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("MaPhanCong");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaPhuongTien");

                    b.HasIndex("MaDon", "TrangThai");

                    b.ToTable("PhanCongGiaoHangs");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.PhuongTien", b =>
                {
                    b.Property<int>("MaPhuongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhuongTien"));

                    b.Property<string>("AnhXe")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("BienSo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiPhuongTien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TaiTrongToiDa")
                        .HasColumnType("decimal(10,2)");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("MaPhuongTien");

                    b.HasIndex("BienSo")
                        .IsUnique();

                    b.ToTable("PhuongTiens", t =>
                        {
                            t.HasCheckConstraint("CK_PhuongTien_TaiTrong", "[TaiTrongToiDa] > 0");
                        });
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.TinTuc", b =>
                {
                    b.Property<int>("MaTinTuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTinTuc"));

                    b.Property<string>("AnhBia")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("BieuTuong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("ChuyenMuc")
                        .HasColumnType("tinyint");

                    b.Property<bool>("HienThi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TomTat")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MaTinTuc");

                    b.HasIndex("HienThi", "NgayDang");

                    b.ToTable("TinTucs");

                    b.HasData(
                        new
                        {
                            MaTinTuc = 1,
                            BieuTuong = "bi-cloud-lightning-rain",
                            ChuyenMuc = (byte)0,
                            HienThi = true,
                            NgayDang = new DateTime(2026, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDang = "Quản trị hệ thống",
                            NoiDung = "Do ảnh hưởng của mưa lớn kéo dài, một số tuyến giao hàng ngoại thành và liên tỉnh có thể chậm hơn ngày giao dự kiến từ 1 đến 2 ngày.\nTrong thời gian này, GiaoNhanh áp dụng các biện pháp sau:\n- Hàng hóa được bọc chống nước trước khi đưa lên xe.\n- Nhân viên giao hàng gọi điện cho người nhận trước khi đến để hẹn thời gian phù hợp.\n- Đơn chưa giao được vì thời tiết sẽ được ghi rõ lý do trong lịch sử giao nhận và sắp xếp giao lại sớm nhất.\nQuý khách có thể theo dõi trạng thái đơn bất cứ lúc nào tại mục Tra cứu đơn bằng mã đơn và số điện thoại người nhận.",
                            TieuDe = "Mùa mưa bão: một số đơn có thể giao chậm 1 – 2 ngày",
                            TomTat = "Tại các khu vực chịu ảnh hưởng của mưa lớn, thời gian giao hàng có thể kéo dài hơn dự kiến. Hàng hóa vẫn được bảo quản an toàn."
                        },
                        new
                        {
                            MaTinTuc = 2,
                            BieuTuong = "bi-cash-coin",
                            ChuyenMuc = (byte)1,
                            HienThi = true,
                            NgayDang = new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDang = "Quản trị hệ thống",
                            NoiDung = "Khi tạo đơn, người gửi có thể nhập số tiền thu hộ – đây là tiền hàng mà nhân viên giao hàng sẽ thu của người nhận.\nQuy trình đối soát tiền thu hộ tại GiaoNhanh:\n- Giao thành công: nhân viên thu tiền thu hộ (cộng phí ship nếu người nhận trả phí).\n- Nhân viên nộp số tiền đã thu về công ty qua ví trên ứng dụng.\n- Công ty xác nhận đã nhận tiền, đơn chuyển sang Hoàn tất và được đối soát.\n- Người gửi nhận lại tiền thu hộ, trừ phí ship nếu người gửi là người trả phí.\nNhân viên giao hàng chỉ được hưởng tiền ship của các đơn giao thành công, không được hưởng tiền thu hộ.",
                            TieuDe = "Thu hộ tiền hàng: người gửi nhận lại tiền khi nào?",
                            TomTat = "Tiền thu hộ là tiền hàng của người gửi. Nhân viên giao hàng chỉ giữ hộ và nộp lại công ty để đối soát trả người gửi."
                        },
                        new
                        {
                            MaTinTuc = 3,
                            BieuTuong = "bi-calculator",
                            ChuyenMuc = (byte)2,
                            HienThi = true,
                            NgayDang = new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDang = "Quản trị hệ thống",
                            NoiDung = "Phí vận chuyển của mỗi đơn gồm ba phần và được hiển thị trước khi quý khách xác nhận tạo đơn:\n- Phí cơ bản theo khu vực giao (xem Bảng giá trên trang chủ).\n- Phụ phí khối lượng: phần vượt 2 kg tính 5.000 đ cho mỗi kg.\n- Phụ phí loại hàng: hàng dễ vỡ, hàng giá trị cao… được cộng thêm theo hệ số của từng loại.\nQuý khách có thể chọn người gửi hoặc người nhận trả phí ship. Nếu người nhận trả, nhân viên sẽ thu phí ship cùng tiền thu hộ khi giao.",
                            TieuDe = "Cách tính phí vận chuyển minh bạch",
                            TomTat = "Phí được hệ thống tự tính ngay khi tạo đơn theo khu vực giao, khối lượng và loại hàng – không phát sinh thêm khi giao."
                        },
                        new
                        {
                            MaTinTuc = 4,
                            BieuTuong = "bi-box-seam",
                            ChuyenMuc = (byte)1,
                            HienThi = true,
                            NgayDang = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDang = "Quản trị hệ thống",
                            NoiDung = "Hàng dễ vỡ như đồ gốm sứ, thủy tinh, thiết bị điện tử cần được đóng gói kỹ trước khi giao cho nhân viên lấy hàng:\n- Dùng thùng carton cứng, còn nguyên vẹn, kích thước vừa với hàng.\n- Bọc từng món bằng màng xốp hơi, chèn kín khoảng trống để hàng không xê dịch.\n- Dán băng keo chữ H ở mặt trên và mặt đáy thùng.\n- Chọn đúng loại hàng khi tạo đơn và ghi chú \"Hàng dễ vỡ, nhẹ tay\" để nhân viên lưu ý.\nKhai báo đúng khối lượng giúp hệ thống xếp xe phù hợp với tải trọng, tránh chèn ép hàng.",
                            TieuDe = "Đóng gói hàng dễ vỡ đúng cách để giao an toàn",
                            TomTat = "Một vài lưu ý đơn giản khi đóng gói giúp hàng dễ vỡ đến tay người nhận nguyên vẹn."
                        },
                        new
                        {
                            MaTinTuc = 5,
                            BieuTuong = "bi-arrow-repeat",
                            ChuyenMuc = (byte)2,
                            HienThi = true,
                            NgayDang = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDang = "Quản trị hệ thống",
                            NoiDung = "Khi không liên lạc được người nhận hoặc người nhận hẹn lại, nhân viên sẽ cập nhật trạng thái Giao không thành công kèm lý do cụ thể.\nSau đó bộ phận điều phối sẽ sắp xếp giao lại:\n- Mỗi đơn được giao tối đa 3 lần (lần đầu và các lần giao lại).\n- Mỗi lần giao lại đều được ghi vào lịch sử giao nhận: ai giao, lúc nào, kết quả ra sao.\n- Quá số lần giao, công ty sẽ liên hệ người gửi để hủy hoặc chuyển hoàn đơn.\nĐể đơn được giao thành công ngay lần đầu, quý khách vui lòng nhập đúng số điện thoại và địa chỉ người nhận.",
                            TieuDe = "Đơn giao không thành công được xử lý thế nào?",
                            TomTat = "Mỗi đơn được giao tối đa 3 lần. Lý do không giao được luôn được ghi lại để quý khách theo dõi."
                        },
                        new
                        {
                            MaTinTuc = 6,
                            BieuTuong = "bi-pencil-square",
                            ChuyenMuc = (byte)2,
                            HienThi = true,
                            NgayDang = new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDang = "Quản trị hệ thống",
                            NoiDung = "Sau khi tạo đơn, quý khách có thể tự thay đổi thông tin người nhận, khối lượng, khu vực giao hoặc hủy đơn tại trang Đơn hàng của tôi.\n- Được sửa / hủy: khi đơn đang Chờ phân công hoặc Đã phân công (nhân viên chưa lấy hàng).\n- Không được sửa / hủy: khi nhân viên đã nhận hàng – lúc này vui lòng liên hệ tổng đài 1900 1515 để được hỗ trợ.\nKhi sửa khối lượng, khu vực hoặc loại hàng, phí vận chuyển được hệ thống tính lại và ghi vào lịch sử đơn.",
                            TieuDe = "Sửa hoặc hủy đơn: khi nào vẫn còn kịp?",
                            TomTat = "Quý khách tự sửa thông tin hoặc hủy đơn ngay trên tài khoản khi nhân viên chưa đến lấy hàng."
                        });
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.DonGiaoHang", b =>
                {
                    b.HasOne("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.GiaoDichVi", "GiaoDichNop")
                        .WithMany("DonNop")
                        .HasForeignKey("MaGiaoDichNop")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.KhachHang", "KhachHang")
                        .WithMany("DonGiaoHangs")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.KhuVuc", "KhuVuc")
                        .WithMany("DonGiaoHangs")
                        .HasForeignKey("MaKhuVuc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.LoaiHang", "LoaiHang")
                        .WithMany("DonGiaoHangs")
                        .HasForeignKey("MaLoaiHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiaoDichNop");

                    b.Navigation("KhachHang");

                    b.Navigation("KhuVuc");

                    b.Navigation("LoaiHang");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.GiaoDichVi", b =>
                {
                    b.HasOne("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.NhanVienGiaoHang", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.KhachHang", b =>
                {
                    b.HasOne("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("KhachHang")
                        .HasForeignKey("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.KhachHang", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.LichSuGiaoNhan", b =>
                {
                    b.HasOne("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.DonGiaoHang", "DonGiaoHang")
                        .WithMany("LichSus")
                        .HasForeignKey("MaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonGiaoHang");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.NhanVienGiaoHang", b =>
                {
                    b.HasOne("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.KhuVuc", "KhuVucPhuTrach")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaKhuVucPhuTrach")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("NhanVienGiaoHang")
                        .HasForeignKey("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.NhanVienGiaoHang", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("KhuVucPhuTrach");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.PhanCongGiaoHang", b =>
                {
                    b.HasOne("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.DonGiaoHang", "DonGiaoHang")
                        .WithMany("PhanCongs")
                        .HasForeignKey("MaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.NhanVienGiaoHang", "NhanVien")
                        .WithMany("PhanCongs")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.PhuongTien", "PhuongTien")
                        .WithMany("PhanCongs")
                        .HasForeignKey("MaPhuongTien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonGiaoHang");

                    b.Navigation("NhanVien");

                    b.Navigation("PhuongTien");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.DonGiaoHang", b =>
                {
                    b.Navigation("LichSus");

                    b.Navigation("PhanCongs");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.GiaoDichVi", b =>
                {
                    b.Navigation("DonNop");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.KhachHang", b =>
                {
                    b.Navigation("DonGiaoHangs");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.KhuVuc", b =>
                {
                    b.Navigation("DonGiaoHangs");

                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.LoaiHang", b =>
                {
                    b.Navigation("DonGiaoHangs");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.NhanVienGiaoHang", b =>
                {
                    b.Navigation("PhanCongs");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.PhuongTien", b =>
                {
                    b.Navigation("PhanCongs");
                });

            modelBuilder.Entity("QuanLyGiaoNhan_UNETI5_DHTI17A4.Models.TaiKhoan", b =>
                {
                    b.Navigation("KhachHang");

                    b.Navigation("NhanVienGiaoHang");
                });
#pragma warning restore 612, 618
        }
    }
}
